version: 2.1
jobs:
  build-test-package:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run: mvn -B -ntp compile
      - run: mvn -B -ntp verify
      - run: mvn -B -ntp -DskipTests package
      - store_test_results:
          path: target/surefire-reports
workflows:
  ci:
    jobs: [build-test-package]
